services:
  postgresql_database:
    image: postgres
    environment:
      POSTGRES_DB: 'ecmorelia_database'
      POSTGRES_USER: 'posgres'
      POSTGRES_PASSWORD: '1234'
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  backend_de_node_js:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecmorelia_backend_image
    ports:
      - '3000:3000'

  